title               : Aydan Ghazani
description         : >-                               # >- means to ignore newlines until "url:"
                      Software Engineer <br/> ghazani.aydan (at) gmail.com

github_user: 4ydan

exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
